# Generated by Django 4.0.2 on 2022-02-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('D', 'DONE'), ('C', 'CANCELLED')], default='P', max_length=1),
        ),
    ]
