# Generated by Django 4.0.2 on 2022-02-17 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(choices=[('P', 'PENDING'), ('D', 'DONE'), ('C', 'CANCELLED')], max_length=1, null=True)),
                ('new_status', models.CharField(choices=[('P', 'PENDING'), ('D', 'DONE'), ('C', 'CANCELLED')], max_length=1, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
